name: Selective Deployment

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  check-changes:
    # คงเดิม...

  build-and-deploy-frontend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Step เพิ่มเติมสำหรับ build image
      - name: Build Frontend Image
        run: |
          docker build -t myapp-frontend:${{ github.sha }} ./frontend
          
      # Step เพิ่มเติมสำหรับ push image
      - name: Push to Registry
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push myapp-frontend:${{ github.sha }}
      
      - name: Deploy Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/app
            ./scripts/update-frontend.sh