name: Frontend Deployment

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/tags/') && 'production' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Set deployment tag
        id: set-tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG=dev-${GITHUB_SHA}" >> $GITHUB_ENV
          fi

      - name: Build and push Frontend Docker image
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/frontend:${TAG} .
          docker push ${{ secrets.DOCKER_REGISTRY }}/frontend:${TAG}

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            COMPOSE_FILE="docker-compose.prod.yml"
          else
            COMPOSE_FILE="docker-compose.dev.yml"
          fi
          
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} "cd /opt/app && \
          export TAG=$TAG && \
          export DOCKER_REGISTRY=$DOCKER_REGISTRY && \
          docker-compose -f infra/docker/$COMPOSE_FILE pull frontend && \
          docker-compose -f infra/docker/$COMPOSE_FILE up -d frontend"